# Generated by Django 3.2.12 on 2022-09-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Memoria',
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('tiempo', models.IntegerField(blank=True, null=True)),
                ('tiempo_restante', models.IntegerField(blank=True, default=0, null=True)),
                ('tamaño', models.IntegerField(blank=True, null=True)),
                ('prioridad', models.SmallIntegerField(default=0)),
                ('estado', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
            },
        ),
    ]
