# Generated by Django 3.2.12 on 2022-09-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaProcesos', '0002_alter_proceso_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.SmallIntegerField(choices=[(0, 'En espera'), (1, 'En ejecucion'), (2, 'Terminado')], default=0),
        ),
    ]
